theme: jekyll-theme-minimal
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: "default"
      read_time: true
      comments: true
      share: true
      related: true
